services:
  - type: web
    name: securebank-app
    env: node
    region: singapore          # Closest to India for fast response
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        value: 
      - key: OWNER_EMAIL
        value: 
      - key: JWT_SECRET
        value: 
