services:
  - type: web
    name: securebank-app
    env: node
    region: singapore          # closest to India
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GMAIL_USER
        sync: false            # set manually in Render dashboard
      - key: GMAIL_APP_PASSWORD
        sync: false            # set manually in Render dashboard
      - key: OWNER_EMAIL
        sync: false            # set manually in Render dashboard
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false            # set manually in Render dashboard (paste JSON string)
